services:
  todo-api-dev-mongodb1:
    container_name: todo-api-dev-mongodb1
    image: mongo:7.0-rc-jammy
    networks:
      mongors-network:
        ipv4_address: 192.168.91.2
    ports:
      - 27021:27017
    restart: always
    volumes:
      - ./rs-init.sh:/scripts/rs-init.sh
    depends_on:
      - todo-api-dev-mongodb2
    # command: "--replSet rs0 --bind_ip localhost,todo-api-dev-mongodb1"
    command: "--replSet rs0 --bind_ip_all"

  todo-api-dev-mongodb2:
    container_name: todo-api-dev-mongodb2
    image: mongo:7.0-rc-jammy
    networks:
      mongors-network:
        ipv4_address: 192.168.91.3
    ports:
      - 27022:27017
    restart: always
    depends_on:
      - todo-api-dev-mongodb3
    # command: "--replSet rs0 --bind_ip localhost,todo-api-dev-mongodb2"
    command: "--replSet rs0 --bind_ip_all"

  todo-api-dev-mongodb3:
    container_name: todo-api-dev-mongodb3
    image: mongo:7.0-rc-jammy
    networks:
      mongors-network:
        ipv4_address: 192.168.91.4
    ports:
      - 27023:27017
    restart: always
    # command: "--replSet rs0 --bind_ip localhost,todo-api-dev-mongodb3"
    command: "--replSet rs0 --bind_ip_all"

# networks:
#   mongors-network:
networks:
  mongors-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.91.0/24"